task_update_rules:
  - query_group_id: 1
    update_method: 'aggregate_by_task'
    options:
      metric_type: 'cpu'
      aggregation_type: 'median'
server_configs:
  elasticsearch:
    url: 'http://localhost:9200'
    api_key: 'your_api_key_here'
    options:
      timeout: 30
  prometheus:
    url: 'http://localhost:8088/api/v1/query'
    options:
      timeout: 30
query_groups:
- id: 1
  backend: prometheus
  options:
    query_time_offset: 1
  queries:
  - quantile_over_time(0.5, cpu_usage_node_id[150s])

  - quantile_over_time(0.5, cpu_usage_node_id[20m])

  - quantile_over_time(0.9, cpu_usage_node_id[150s])

  - quantile_over_time(0.9, cpu_usage_node_id[20m])

  - quantile_over_time(0.95, cpu_usage_node_id[150s])

  - quantile_over_time(0.95, cpu_usage_node_id[20m])
