servers:
- name: prometheus
  url: http://localhost:9090
- name: sketchdb
  url: http://localhost:8088

query_groups:
- id: 1
  repetitions: 5
  repetition_delay: 10
  # starting_delay: 0
  options:
    query_time_offset: 10
  queries:
  - 'sum_over_time(node_cpu_seconds_total[1m])'
  # - 'sum_over_time(node_cpu_seconds_total[30s])'
