# Configuration file for components/repositories
# This file defines the list of all components used across the project
# Used by installation and deployment scripts to maintain consistency

Utilities
CommonDependencies
#FlinkSketch
#QueryEngine
QueryEngineRust
PrometheusClient
Controller
#prometheus-kafka-adapter
ArroyoSketch
ExecutionUtilities
arroyo
PrometheusExporters
prometheus-benchmark
