aggregations:
- aggregationId: 1
  aggregationSubType: sum
  aggregationType: MultipleSum
  labels:
    aggregated:
    # - instance
    # - job
    - label_0
    - label_1
    - label_2
    grouping:
    - instance
    - job
    rollup: []
  metric: fake_metric_total
  parameters: {}
  spatialFilter: ''
  tumblingWindowSize: 10
# - aggregationId: 2
#   aggregationSubType: ''
#   aggregationType: MultipleIncrease
#   labels:
#     aggregated:
#     - instance
#     - job
#     - label_0
#     - label_1
#     - label_2
#     grouping: []
#     rollup: []
#   metric: fake_metric_total
#   parameters: {}
#   spatialFilter: ''
#   tumblingWindowSize: 10
# - aggregationId: 3
#   aggregationSubType: sum
#   aggregationType: MultipleSum
#   labels:
#     aggregated:
#     - instance
#     - job
#     grouping: []
#     rollup:
#     - label_0
#     - label_1
#     - label_2
#   metric: fake_metric_total
#   parameters: {}
#   spatialFilter: ''
#   tumblingWindowSize: 10
- aggregationId: 4
  aggregationSubType: sum
  aggregationType: MultipleSum
  labels:
    aggregated:
    - label_0
    grouping: []
    rollup:
    - instance
    - job
    - label_1
    - label_2
  metric: fake_metric_total
  parameters: {}
  spatialFilter: ''
  tumblingWindowSize: 10
metrics:
  fake_metric_total:
  - instance
  - job
  - label_0
  - label_1
  - label_2
