supported_aggs:
  percentiles:
    metrics:
      - cpu_cores
      - memory_gb
      - network_mbps
    metrics_with_labels:
      labels:
        - cluster
        - task
        - cluster;task
      metrics:
        - cpu_cores
        - memory_gb
        - network_mbps
  # For "Who is the top consumer?" queries
  top_entities:
    metrics:
      - cpu_cores
      - memory_gb
      - network_mbps
    metrics_with_labels:
      labels:
        - cluster
        - task
        - cluster;task
      metrics:
        - cpu_cores
        - memory_gb
        - network_mbps
  # For "Total value for each categories" queries
  cumulative:
    metrics:
      - cpu_cores
      - memory_gb
      - network_mbps
    metrics_with_labels:
      labels:
        - cluster
        - task
        - cluster;task
      metrics:
        - cpu_cores
        - memory_gb
        - network_mbps
